ProyectoAdministradorTienda/Models/ErrorViewModel.cs
namespace ProyectoAdministradorTienda.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoAdministradorTienda/Models/ProductoColorTalla.cs
namespace ProyectoAdministradorTienda.Models
{
    public class ProductoColorTalla
    {
        public int idProductoColorTalla { get; set; }
        public Producto Producto { get; set; }
        public ColorProducto ColorProducto { get; set; }
        public TallaProducto TallaProducto { get; set; }

        public int stock { get; set; }
        public int stockMin { get; set; }
        public int stockMax { get; set; }
        public double precio { get; set; }
    }
}

ProyectoAdministradorTienda/Controllers/ProductoColorTallaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class ProductoColorTallaController : Controller
    {
        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public ProductoColorTallaController(IAPIService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<ProductoColorTalla> tipos = await _apiService.GetProductosColresTallas();
            return View(tipos);
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["IdProducto"], out int idProducto))
            {
                ProductoColorTalla tipo2 = await _apiService.GetProductoColorTalla(idProducto);
                if (tipo2 != null)
                {
                    return View("Details",tipo2);
                }
            }

            return View("ErrorView");
        }


        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int IdProducto)
            {
                //Console.WriteLine(color..ToString());
                ProductoColorTalla tipo2 = await _apiService.GetProductoColorTalla(IdProducto);
                if (tipo2 != null)
                {
                    return View(tipo2);
                }
                else
                {
                    return View("Error");
                }
                return RedirectToAction("Index");
            }

        // GET: ProductoController/Create
        public async Task<IActionResult> Create()
        {
            // Obtener la lista de tipos de producto
            List<Producto> tipos = await _apiService.GetProductos();

            // Almacena la lista de tipos de producto en ViewBag
            ViewBag.Productos = new SelectList(tipos, "idProduto", "nombre");

            List<ColorProducto> colores = await _apiService.GetColores();
            ViewBag.Colores = new SelectList(colores, "idColorProducto", "nombre");

            List<TallaProducto> tallas = await _apiService.GetTalla();
            ViewBag.Tallas = new SelectList(tallas, "idTallaProducto", "talla");

            return View();


        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductoColorTallaCrea productoapto)
        {
            ProductoColorTallaCrea tipo1 = await _apiService.PostProductoColorTalla(productoapto);
            return RedirectToAction("Index");
        }



        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int idProducto)
        {
            ProductoColorTalla tipo = await _apiService.GetProductoColorTalla(idProducto);
            if (tipo != null)
            {
                return View(tipo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductoColorTallaCrea productoapro)
        {
            //Console.WriteLine(productoapro.idProduto.ToString());
            //Console.WriteLine(productoapro.nombre.ToString());
            ProductoColorTalla tipo2 = await _apiService.GetProductoColorTalla(productoapro.idProductoColorTalla);
            if (tipo2 != null)
            {
                ProductoColorTallaCrea tipo3 = await _apiService.PutProducto(productoapro.idProductoColorTalla, productoapro);

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int idProducto)
        {
            Boolean producto2 = await _apiService.DeleteProductoColorTalla(idProducto);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ProyectoAdministradorTienda/Views/ProductoColorTalla/Create.cshtml
@model ProductoColorTallaCrea

@{
    ViewData["Title"] = "Creación de Productos";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se crean los productos.</p>

<form method="post">
    <div class="mb-3">
        <label asp-for="stock" class="form-label">Stock</label>
        <input asp-for="stock" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="stockMax" class="form-label">Stock Máximo</label>
        <input asp-for="stockMax" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="stockMin" class="form-label">Stock Minimo</label>
        <input asp-for="stockMin" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="precio" class="form-label">Precio</label>
        <input asp-for="precio" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="productoIdProduto" class="form-label">Tipo de Producto</label>
        @Html.DropDownListFor(model => model.productoIdProduto, (IEnumerable<SelectListItem>)ViewBag.Productos, "Selecciona un producto", new { @class = "form-control" })

    </div>
    <div class="mb-3">
        <label asp-for="colorProductoIdColorProducto" class="form-label">Tipo de Producto</label>
        @Html.DropDownListFor(model => model.colorProductoIdColorProducto, (IEnumerable<SelectListItem>)ViewBag.Colores, "Selecciona un color", new { @class = "form-control" })

    </div>
    <div class="mb-3">
        <label asp-for="tallaProductoIdTallaProducto" class="form-label">Tipo de Producto</label>
        @Html.DropDownListFor(model => model.tallaProductoIdTallaProducto, (IEnumerable<SelectListItem>)ViewBag.Tallas, "Selecciona una talla", new { @class = "form-control" })

    </div>
    <div class="row">
        <div class="col-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        <div class="col-6">
            <a asp-action="Cancelar" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/ProductoColorTalla/Details.cshtml
@model ProductoColorTalla

@{
    ViewData["Title"] = "Detalles Producto";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se muestran los detalles de los Productos.</p>

<form>
    <div class="mb-3">
        <label class="form-label">Tipo producto Nombre</label>
        <input asp-for="Producto.nombre" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Color</label>
        <input asp-for="ColorProducto.nombre" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Talla</label>
        <input asp-for="TallaProducto.talla" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Stock</label>
        <input asp-for="stock" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Stock</label>
        <input asp-for="stockMax" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Stock</label>
        <input asp-for="stockMin" class="form-control " readonly />
    </div>
    <div class="row">
        <div class="col-6">
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index","ProductoColorTalla")'">Volver</button>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/ProductoColorTalla/Edit.cshtml
@model ProductoColorTalla
@{
    ViewData["Title"] = "Detalles Producto";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se editan los detalles de los Productos.</p>

<form method="post" >
    <div class="mb-3">
        <label class="form-label">Codigo del Producto</label>
        <input asp-for="idProductoColorTalla" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Tipo producto Nombre</label>
        <input asp-for="Producto.nombre" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Color</label>
        <input asp-for="ColorProducto.nombre" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Talla</label>
        <input asp-for="TallaProducto.talla" class="form-control " readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Stock</label>
        <input asp-for="stock" class="form-control "/>
    </div>
    <div class="mb-3">
        <label class="form-label">Stock Minimo</label>
        <input asp-for="stockMin" class="form-control " />
    </div>
    <div class="mb-3">
        <label class="form-label">Stock Maximo</label>
        <input asp-for="stockMax" class="form-control " />
    </div>
    <div class="mb-3">
        <label class="form-label">Precio</label>
        <input asp-for="precio" class="form-control " />
    </div>
   
    <div class="row">
        <div class="col-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        <div class="col-6">
            <a asp-action="Cancelar" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/ProductoColorTalla/ErrorView.cshtml
@{
    ViewData["Title"] = "Error";
}

<h1>Error</h1>
<p>@ViewBag.ErrorMessage</p>
<button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index","ProductoColorTalla")'">Volver</button>

ProyectoAdministradorTienda/Views/ProductoColorTalla/Index.cshtml
<!-- Se debe incluir la biblioteca para importr los iconos -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@model List<ProductoColorTalla>
@{
    ViewData["Title"] = "Productos Registrados";
}
<h1>@ViewData["Title"]</h1>
<button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create","ProductoColorTalla")'">Nuevo Producto</button>

<p>Esta página muestra la Lista de Productos Registrados.</p>

<p>Buscar por ID:</p>
<form method="get" action="@Url.Action("Search", "ProductoColorTalla")">
    <div class="mb-3">
        <label class="form-label">ID:</label>
        <input type="text" name="IdProducto" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre del Producto</th>
            <th scope="col">Color</th>
            <th scope="col">Talla</th>
            <th scope="col">Stock</th>
            <th scope="col">Stock Min</th>
            <th scope="col">Stock Max</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.idProductoColorTalla</td>
                <td>@item.Producto.nombre</td>
                <td>@item.ColorProducto.nombre</td>
                <td>@item.TallaProducto.talla</td>
                <td>@item.stock</td>
                <td>@item.stockMin</td>
                <td>@item.stockMax</td>
                <td><a asp-action="Edit" asp-route-IdProducto="@item.idProductoColorTalla" type="button" class="btn btn-success"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;<a asp-action="Details" asp-route-IdProducto="@item.idProductoColorTalla" type="button" class="btn btn-primary"><i class="fa fa-plus-square-o" aria-hidden="true"></i></a>&nbsp;<a asp-action="Delete" asp-route-IdProducto="@item.idProductoColorTalla" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
            </tr>
        }
    </tbody>