ProyectoAdministradorTienda/Controllers/ColorProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class ColorProductoController : Controller
    {
        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public ColorProductoController(IAPIService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<ColorProducto> productos = await _apiService.GetColores();
            return View(productos);
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["IdProducto"], out int idProducto))
            {
                ColorProducto tipo2 = await _apiService.GetColor(idProducto);
                if (tipo2 != null)
                {
                    return View("Details", tipo2);
                }
            }

            return View("ErrorView");
        }

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int idColorProducto)
        {
            //Console.WriteLine(color..ToString());
            ColorProducto color2 = await _apiService.GetColor(idColorProducto);
            if (color2 != null)
            {
                return View(color2);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ColorProducto color)
        {
            ColorProducto color1 = await _apiService.PostColor(color);
            return RedirectToAction("Index");
        }



        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int idColorProducto)
        {
            ColorProducto producto = await _apiService.GetColor(idColorProducto);
            if (producto != null)
            {
                return View(producto);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ColorProducto color)
        {
            ColorProducto color2 = await _apiService.GetColor(color.idColorProducto);
            if (color2 != null)
            {
                ColorProducto color3 = await _apiService.PutColor(color.idColorProducto, color);

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int IdColorProducto)
        {
            Boolean producto2 = await _apiService.DeleteColor(IdColorProducto);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ProyectoAdministradorTienda/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class ProductoController : Controller
    {
        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public ProductoController(IAPIService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<Producto> tipos = await _apiService.GetProductos();
            return View(tipos);
        }

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int IdProducto)
        {
            //Console.WriteLine(color..ToString());
            Producto tipo2 = await _apiService.GetProducto(IdProducto);
            if (tipo2 != null)
            {
                return View(tipo2);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["IdProducto"], out int idProducto))
            {
                Producto tipo2 = await _apiService.GetProducto(idProducto);
                if (tipo2 != null)
                {
                    return View("Details", tipo2);
                }
            }

            return View("ErrorView");
        }

        // GET: ProductoController/Create
        public async Task<IActionResult> Create()
        {
            // Obtener la lista de tipos de producto
            List<TipoProducto> tipos = await _apiService.GetTipos();

            // Almacena la lista de tipos de producto en ViewBag
            ViewBag.TipoProductos = new SelectList(tipos, "idTipoProducto", "nombre");

            return View();
        
        
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductoCrea productoapto)
        {
            ProductoCrea tipo1 = await _apiService.PostProducto(productoapto);
            return RedirectToAction("Index");
        }



        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int idProducto)
        {
            Producto tipo = await _apiService.GetProducto(idProducto);
            if (tipo != null)
            {
                return View(tipo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductoCrea productoapro)
        {
            Console.WriteLine(productoapro.idProduto.ToString());
            Console.WriteLine(productoapro.nombre.ToString());
            Producto tipo2 = await _apiService.GetProducto(productoapro.idProduto);
            if (tipo2 != null)
            {
                ProductoCrea tipo3 = await _apiService.PutProducto(productoapro.idProduto, productoapro);

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int idProducto)
        {
            Boolean producto2 = await _apiService.DeleteProducto(idProducto);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ProyectoAdministradorTienda/Controllers/TipoProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class TipoProductoController : Controller
    {
        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public TipoProductoController(IAPIService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<TipoProducto> tipos = await _apiService.GetTipos();
            return View(tipos);
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["IdProducto"], out int idProducto))
            {
                TipoProducto tipo2 = await _apiService.GetTipo(idProducto);
                if (tipo2 != null)
                {
                    return View("Details", tipo2);
                }
            }

            return View("ErrorView");
        }

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int IdTipoProducto)
        {
            //Console.WriteLine(color..ToString());
            TipoProducto tipo2 = await _apiService.GetTipo(IdTipoProducto);
            if (tipo2 != null)
            {
                return View(tipo2);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TipoProducto tipoapto)
        {
            TipoProducto tipo1 = await _apiService.PostTipo(tipoapto);
            return RedirectToAction("Index");
        }



        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int IdTipoProducto)
        {
            TipoProducto tipo = await _apiService.GetTipo(IdTipoProducto);
            if (tipo != null)
            {
                return View(tipo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TipoProducto tipoapro)
        {
            Console.WriteLine(tipoapro.idTipoProducto.ToString());
            Console.WriteLine(tipoapro.nombre.ToString());
            TipoProducto tipo2 = await _apiService.GetTipo(tipoapro.idTipoProducto);
            if (tipo2 != null)
            {
                TipoProducto tipo3 = await _apiService.PutTipo(tipoapro.idTipoProducto, tipoapro);

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int IdTipoProducto)
        {
            Boolean producto2 = await _apiService.DeleteTipo(IdTipoProducto);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }




        //metodos para vista producto
        /*public async Task<IActionResult> Createlista()
        {
            // Obtener la lista de tipos de producto
            List<TipoProducto> tipos = await _apiService.GetTipos();

            // Crear una lista de SelectListItem para la lista desplegable
            ViewBag.TipoProductos = new SelectList(tipos,"nombre");

            return View();
        }*/

        /*public async Task<IActionResult> Createlista()
        {
            // Obtener la lista de tipos de producto
            List<TipoProducto> tipos = await _apiService.GetTipos();

            // Almacena la lista de tipos de producto en ViewBag
            ViewBag.TipoProductos = new SelectList(tipos, "idTipoProducto", "nombre");

            return View();
        }*/


    }
}

ProyectoAdministradorTienda/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class UsuarioController : Controller
    {

        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public UsuarioController(IAPIService apiService)
        {
            _apiService = apiService;
        }
        public async Task<IActionResult> Index()
        {
            List<Usuario> tipos = await _apiService.GetUsuarios();
            return View(tipos);
        }

        // GET: ProductoController
        public async Task<IActionResult> Login()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string Login, string Contrasenia)
        {
            //List<Producto> tipos = await _apiService.GetProductos();

            Usuario usuario = await _apiService.GetValidacion(Login,Contrasenia);
            if(usuario == null)
            {
                ViewBag.ErrorMessage = "Credenciales incorrectas. Vuelva a intentarlo.";
                return View ();
            }
            else
            {
                return RedirectToAction("Index","Home");
            }

        }

        // GET: ProductoController/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            Usuario usuario1 = await _apiService.PostUsuario(usuario);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["idUsuario"], out int idUsario))
            {
                Usuario tipo2 = await _apiService.GetUsuario(idUsario);
                if (tipo2 != null)
                {
                    return View("Details", tipo2);
                }
            }

            return View("ErrorView");
        }
        

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int idUsuario)
        {
            //Console.WriteLine(color..ToString());
            Usuario tipo2 = await _apiService.GetUsuario(idUsuario);
            if (tipo2 != null)
            {
                return View(tipo2);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int idUsuario)
        {
            Usuario tipo = await _apiService.GetUsuario(idUsuario);
            if (tipo != null)
            {
                return View(tipo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Usuario usuarioasd)
        {
           
            Usuario tipo2 = await _apiService.GetUsuario(usuarioasd.idUsuario);
            if (tipo2 != null)
            {
                Usuario tipo3 = await _apiService.PutUsuario(usuarioasd.idUsuario, usuarioasd);

                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int idUsuario)
        {
            Boolean producto2 = await _apiService.DeleteUsuario(idUsuario);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ProyectoAdministradorTienda/Views/Shared/_Layout InicioSesion.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoAdministradorTienda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapSandstone.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoAdministradorTienda.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <label style="color: #ffffff;">BIENVENIDO ADMINISTRADOR DE LA TIENDA</label>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex">
                        
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
           
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoAdministradorTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoAdministradorTienda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapSandstone.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoAdministradorTienda.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bienvenido</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ColorProducto" asp-action="Index">ColorProducto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TallaProducto" asp-action="Index">TallaProducto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoProducto" asp-action="Index">TipoProducto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductoColorTalla" asp-action="Index">ProductoColorTalla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Gestión de Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2023 - ProyectoAdministradorTienda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>