ProyectoAdministradorTienda/Models/ErrorViewModel.cs
namespace ProyectoAdministradorTienda.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoAdministradorTienda/Models/TallaProducto.cs
namespace ProyectoAdministradorTienda.Models
{
    public class TallaProducto
    {
        public int idTallaProducto { get; set; }
        public string talla { get; set; }
    }
}

ProyectoAdministradorTienda/Controllers/TallaProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoAdministradorTienda.Models;
using ProyectoAdministradorTienda.Services;

namespace ProyectoAdministradorTienda.Controllers
{
    public class TallaProductoController : Controller
    {
        // GET: ColorProductoController
        private readonly IAPIService _apiService;

        public TallaProductoController(IAPIService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController
        public async Task<IActionResult> Index()
        {
            List<TallaProducto> productos = await _apiService.GetTalla();
            return View(productos);
        }

        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int idTallaProducto)
        {
            //Console.WriteLine(color..ToString());
            TallaProducto talla2 = await _apiService.GetTalla(idTallaProducto);
            if (talla2 != null)
            {
                return View(talla2);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TallaProducto tallapto)
        {
            TallaProducto talla1 = await _apiService.PostTalla(tallapto);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Search()
        {
            if (int.TryParse(Request.Query["IdProducto"], out int idProducto))
            {
                TallaProducto tipo2 = await _apiService.GetTalla(idProducto);
                if (tipo2 != null)
                {
                    return View("Details", tipo2);
                }
            }

            return View("ErrorView");
        }


        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int idTallaProducto)
        {
            TallaProducto talla = await _apiService.GetTalla(idTallaProducto);
            if (talla != null)
            {
                return View(talla);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TallaProducto tallapro)
        {
            Console.WriteLine(tallapro.idTallaProducto.ToString());
            Console.WriteLine(tallapro.talla.ToString());
            TallaProducto talla2 = await _apiService.GetTalla(tallapro.idTallaProducto);
            if (talla2 != null)
            {
                TallaProducto talla3 = await _apiService.PutTalla(tallapro.idTallaProducto, tallapro);

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(int idTallaProducto)
        {
            Boolean producto2 = await _apiService.DeleteTalla(idTallaProducto);
            if (producto2 != false)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ProyectoAdministradorTienda/Views/TallaProducto/Create.cshtml
@model TallaProducto

@{
    ViewData["Title"] = "Creación de Tallas";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se crean las tallas.</p>

<form method="post">
    <div class="mb-3">
        <label class="form-label">Talla</label>
        <input asp-for="talla" class="form-control" />
    </div>
    <div class="row">
        <div class="col-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        <div class="col-6">
            <a asp-action="Cancelar" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/TallaProducto/Details.cshtml
@model TallaProducto

@{
    ViewData["Title"] = "Detalles   Talla";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se muestran los detalles de las tallas.</p>

<form>
    <div class="mb-3">
        <label class="form-label">Talla</label>
        <input asp-for="talla" class="form-control " readonly />
    </div>
    <div class="row">
        <div class="col-6">
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index","TallaProducto")'">Volver</button>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/TallaProducto/Edit.cshtml
@model TallaProducto

@{
    ViewData["Title"] = "Editar Talla";
}

<h1>@ViewData["Title"]</h1>
<p>En esta página se editan las tallas.</p>

<form method="post">
    <div class="mb-3">
        <label class="form-label">Talla</label>
        <input asp-for="talla" class="form-control" />
    </div>
    <div class="row">
        <div class="col-6">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        <div class="col-6">
            <a asp-action="index" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</form>

ProyectoAdministradorTienda/Views/TallaProducto/ErrorView.cshtml
@{
    ViewData["Title"] = "Error";
}

<h1>Error</h1>
<p>@ViewBag.ErrorMessage</p>
<button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index","TallaProducto")'">Volver</button>

ProyectoAdministradorTienda/Views/TallaProducto/Index.cshtml
<!-- Se debe incluir la biblioteca para importr los iconos -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@model List<TallaProducto>
@{
    ViewData["Title"] = "Tallas Registrados";
}
<h1>@ViewData["Title"]</h1>
<button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create","TallaProducto")'">Nueva Talla</button>

<p>Esta página muestra la Lista de Tallas Registrados.</p>

<p>Buscar por ID:</p>
<form method="get" action="@Url.Action("Search", "TallaProducto")">
    <div class="mb-3">
        <label class="form-label">ID:</label>
        <input type="text" name="IdProducto" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Buscar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Talla</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.idTallaProducto</td>
                <td>@item.talla</td>
                <td><a asp-action="Edit" asp-route-idTallaProducto="@item.idTallaProducto" type="button" class="btn btn-success"><i class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;<a asp-action="Details" asp-route-idTallaProducto="@item.idTallaProducto" type="button" class="btn btn-primary"><i class="fa fa-plus-square-o" aria-hidden="true"></i></a>&nbsp;<a asp-action="Delete" asp-route-idTallaProducto="@item.idTallaProducto" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
            </tr>
        }
    </tbody>